version: '3'
services:
  webapp:
    build: 
      context: /WebApp
      dockerfile: DockerFile
    container_name: flask_webapp
    ports:
      - "9696:9696"
    volumes:
      - ./:/app
    depends_on:
      - torchserve

  torchserve:
    image: pytorch/torchserve:latest
    container_name: torch_serve
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./model-store:/home/model-server/model-store
      - ./config.properties:/home/model-server/config.properties
    command: ["torchserve", "--start", "--model-store", "/home/model-server/model-store", "--ts-config", "/home/model-server/config.properties"]
